package qtriptest.pages;

import java.util.UUID;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.pagefactory.AjaxElementLocatorFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class RegisterPage {

    private  RemoteWebDriver driver;
    private String url = "https://qtripdynamic-qa-frontend.vercel.app/pages/register/";
    private final static String REGISTER_PAGE_IDENTIFIER = "/pages/register";

    public static String USER_EMAIL;

    @FindBy(xpath = "//input[@name= 'email']")
    
    private WebElement emailtextbox;


    @FindBy(name = "password")
    
    private WebElement passwordtextbox;

    @FindBy(name = "confirmpassword")
    
    private WebElement confirmtextbox;

    @FindBy(xpath="//button[text()='Register Now']")
    
    private WebElement registerNow;

    @FindBy(xpath="//div[contains(@class, 'card border')]")
    
    private WebElement registerform;
    
   

    public RegisterPage(RemoteWebDriver driver){
        this.driver = driver;
        AjaxElementLocatorFactory ajax = new AjaxElementLocatorFactory(driver, 10);
        PageFactory.initElements(ajax, this);
      
        driver.manage().window().maximize();

    }
    
    public boolean checkRegisterPageNavigation() {
        WebDriverWait wait = new WebDriverWait(driver, 30);
        wait.until(ExpectedConditions.urlContains(url));
        return  driver!=null && driver.getCurrentUrl().contains(REGISTER_PAGE_IDENTIFIER) && registerform!=null &&
        registerform.isDisplayed();
    }


    public  void registernewuser(String email, String password, String confirmpassword, boolean isUserAutoGenerated)throws InterruptedException{
        if(isUserAutoGenerated && emailtextbox!=null && passwordtextbox!=null && confirmtextbox!=null && registerNow!=null){
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOf(emailtextbox));
            email = String.format("testuser_%s@email.com", UUID.randomUUID());

            USER_EMAIL = email;
            emailtextbox.sendKeys(email);
            passwordtextbox.sendKeys(password);
            confirmtextbox.sendKeys(confirmpassword);
            registerNow.click();
        }
    }


}


